# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Hand
                                 A QGIS plugin
 Gera o Height Above Nearest Drainage (HAND)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-09-19
        copyright            : (C) 2025 by João Vitor Lima & Adriano Paz
        email                : jvdsl_off@outlook.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Hand class from file Hand.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .hand_module import Hand
    return Hand(iface)
