# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Hand
                                 A QGIS plugin
 Gera o Height Above Nearest Drainage (HAND)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-09-19
        git sha              : $Format:%H$
        copyright            : (C) 2025 by João Vitor Lima & Adriano Paz
        email                : jvdsl_off@outlook.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import html
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon, QFont
from qgis.PyQt.QtWidgets import QApplication, QAction, QFileDialog, QMessageBox
from qgis.core import QgsMapLayerProxyModel, Qgis, QgsProject, QgsRasterLayer, QgsMapLayer
import qgis.utils

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .hand_module_dialog import HandDialog
import os.path
from pathlib import Path
from osgeo import ogr, gdal, gdalconst
import subprocess
from datetime import datetime
import platform


class Hand:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'Hand_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&HAND Plugin')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None
        self.dlg_hand = HandDialog()
        self.diretorio_atual = os.path.dirname(os.path.abspath(__file__))
        self.projection = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('Hand', message)

    def add_action(
            self,
            icon_path,
            text,
            callback,
            enabled_flag=True,
            add_to_menu=True,
            add_to_toolbar=True,
            status_tip=None,
            whats_this=None,
            parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def traduz_interface(self, idioma: str):
        """Traduz os textos da interface e mensagens para o idioma selecionado ('pt' ou 'en')."""
        self.idioma_atual = idioma
        # Mensagens traduzidas
        self.msgs = {
            'pt': {
                'no_file_selected': 'Nenhum arquivo foi selecionado.',
                'warning_title': 'Atenção',
                'error_title': 'Erro!',
                'info_title': 'Informação!',
                'invalid_filename': 'Por favor, forneça um nome de arquivo válido para salvar o HAND.',
                'invalid_path': 'Por favor, forneca um caminho válido para salvar o HAND.',
                'success': 'Operação realizada com sucesso!',
                'hand_success': 'HAND determinado com sucesso...',
                'hand_start': 'Iniciando processamento do HAND...',
                'hand_convert': 'Convertendo arquivo para GeoTIFF...',
                'hand_add': 'Adicionando arquivo ao QGIS...',
                'hand_error': 'Por favor, verifique se os arquivos enviados correspondem aos que foram solicitados.',
                'cancel_log': '<font>\nATENÇÃO: interrompendo o processo HAND...</font>',
                'success_log': 'Êxito! Operação realizada com sucesso...'
            },
            'en': {
                'no_file_selected': 'No file was selected.',
                'warning_title': 'Warning',
                'error_title': 'Error!',
                'info_title': 'Information!',
                'invalid_filename': 'Please provide a valid file name to save HAND.',
                'invalid_path': 'Please provide a valid path to save HAND.',
                'success': 'Operation completed successfully!',
                'hand_success': 'HAND successfully determined...',
                'hand_start': 'Starting HAND processing...',
                'hand_convert': 'Converting file to GeoTIFF...',
                'hand_add': 'Adding file to QGIS...',
                'hand_error': 'Please check if the provided files match the requested ones.',
                'cancel_log': '<font>\nATTENTION: stopping HAND process...</font>',
                'success_log': 'Success! Operation completed successfully...'
            }
        }
        # ...interface translation as before...
        """Traduz os textos da interface para o idioma selecionado ('pt' ou 'en')."""
        if idioma == 'pt':
            self.dlg_hand.setWindowTitle('HAND Plugin')
            self.dlg_hand.tabWidget.setTabText(0, 'Parâmetros')
            self.dlg_hand.tabWidget.setTabText(1, 'Log')
            self.dlg_hand.label.setText('Bacia Hidrográfica')
            self.dlg_hand.label_2.setText('Modelo Digital de Elevação (MDE)')
            self.dlg_hand.label_3.setText('Direções de Fluxo')
            self.dlg_hand.label_5.setText('Rede de Drenagem')
            self.dlg_hand.label_4.setText(
                'Height Above Nearest Drainage (HAND)')
            self.dlg_hand.groupBox.setTitle('Saída')
            self.dlg_hand.btn_hand.setText('GERAR HAND')
            self.dlg_hand.btn_cancel.setText('CANCELAR')
            self.dlg_hand.label_6.setText('Selecione o idioma:')
            self.dlg_hand.label_11.setToolTip(
                'Adicione a delimitação da bacia hidrográfica. O arquivo deve ser raster (GeoTIFF).')
            self.dlg_hand.label_12.setToolTip(
                'Adicione o modelo digital de elevação. O arquivo deve ser raster (GeoTIFF).')
            self.dlg_hand.label_13.setToolTip(
                'Adicione a direção de fluxo. O arquivo deve ser raster (GeoTIFF).')
            self.dlg_hand.label_14.setToolTip(
                'Adicione a rede de drenagem. O arquivo deve ser raster (GeoTIFF).')
            self.dlg_hand.label_15.setToolTip(
                'Selecione uma pasta para salvar o HAND resultante. O arquivo será adicionado ao projeto QGIS atual!')
            html_description = (
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">'
                'p, li { white-space: pre-wrap; }'
                '</style></head><body style=" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;">'
                '<p align="justify" style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt; font-weight:600; color:#7c7c7c;">Descrição<br /></span></p>'
                '<p align="justify" style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:10pt; color:#838383;">Este plugin determina o Height Above Nearest Drainage (HAND), um descritor de terreno definido pela diferença de elevação entre um ponto de superfície e o ponto mais próximo da rede de drenagem para o qual ele drena¹.</span></p>'
                '<p align="justify" style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; color:#838383;"><br /></p>'
                '<p align="justify" style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; color:#838383;"><br /></p>'
                '<p align="justify" style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:7pt; color:#838383;">¹RENNÓ, C.D.</span><span style=" font-size:7pt; font-style:italic; color:#838383;"> et a</span><span style=" font-size:7pt; color:#838383;">l. “HAND, a new terrain descriptor using SRTM-DEM: mapping terra-firmerainforest environments in Amazonia”. Remote Sensing of Environment 112, 3469-3481, 2008.</span></p></body></html>'
            )
            self.dlg_hand.textEdit.setHtml(html_description)

        else:
            self.dlg_hand.setWindowTitle('HAND Plugin')
            self.dlg_hand.tabWidget.setTabText(0, 'Parameters')
            self.dlg_hand.tabWidget.setTabText(1, 'Log')
            self.dlg_hand.label.setText('Watershed delineation')
            self.dlg_hand.label_2.setText('Digital Elevation Model (DEM)')
            self.dlg_hand.label_3.setText('Flow Directions')
            self.dlg_hand.label_5.setText('River Drainage Network')
            self.dlg_hand.label_4.setText(
                'Height Above Nearest Drainage (HAND)')
            self.dlg_hand.groupBox.setTitle('Output')
            self.dlg_hand.btn_hand.setText('RUN HAND')
            self.dlg_hand.btn_cancel.setText('CANCEL')
            self.dlg_hand.label_6.setText('Select language:')
            self.dlg_hand.label_11.setToolTip(
                'Add the watershed delineation. The file must be a raster type (GeoTIFF).')
            self.dlg_hand.label_12.setToolTip(
                'Add the digital elevation model. The file must be a raster type (GeoTIFF).')
            self.dlg_hand.label_13.setToolTip(
                'Add the flow direction. The file must be a raster type (GeoTIFF).')
            self.dlg_hand.label_14.setToolTip(
                'Add the River Drainage Network. The file must be a raster type (GeoTIFF).')
            self.dlg_hand.label_15.setToolTip(
                'Select a folder to save the resulting HAND. The file will be added to the current QGIS project!')
            html_description = (
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">'
                'p, li { white-space: pre-wrap; }'
                '</style></head><body style=" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;">'
                '<p align="justify" style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt; font-weight:600; color:#7c7c7c;">Description<br /></span></p>'
                '<p align="justify" style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:10pt; color:#838383;">This plugin determines the Height Above Nearest Drainage (HAND), a terrain descriptor defined by the elevation difference between a surface point and the nearest drainage network point to which it drains¹.</span></p>'
                '<p align="justify" style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; color:#838383;"><br /></p>'
                '<p align="justify" style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; color:#838383;"><br /></p>'
                '<p align="justify" style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:7pt; color:#838383;">¹RENNÓ, C.D.</span><span style=" font-size:7pt; font-style:italic; color:#838383;"> et a</span><span style=" font-size:7pt; color:#838383;">l. “HAND, a new terrain descriptor using SRTM-DEM: mapping terra-firmerainforest environments in Amazonia”. Remote Sensing of Environment 112, 3469-3481, 2008.</span></p></body></html>'
            )
            self.dlg_hand.textEdit.setHtml(html_description)

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/hand_module/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'HAND Plugin'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

        # Aplica filtro para apenas raster aos comboboxes
        self.dlg_hand.cb_01.setFilters(QgsMapLayerProxyModel.RasterLayer)
        self.dlg_hand.cb_02.setFilters(QgsMapLayerProxyModel.RasterLayer)
        self.dlg_hand.cb_03.setFilters(QgsMapLayerProxyModel.RasterLayer)
        self.dlg_hand.cb_04.setFilters(QgsMapLayerProxyModel.RasterLayer)

        # Configura selecoes de arquivos
        self.dlg_hand.btn_01.clicked.connect(
            lambda: self.carregaArquivos(self.dlg_hand.cb_01))
        self.dlg_hand.btn_02.clicked.connect(
            lambda: self.carregaArquivos(self.dlg_hand.cb_02))
        self.dlg_hand.btn_03.clicked.connect(
            lambda: self.carregaArquivos(self.dlg_hand.cb_03))
        self.dlg_hand.btn_04.clicked.connect(
            lambda: self.carregaArquivos(self.dlg_hand.cb_04))
        self.dlg_hand.btn_05.clicked.connect(lambda: self.save_buttons())

        # Inicia processamento
        self.dlg_hand.btn_hand.clicked.connect(lambda: self.run_process_hand())
        self.dlg_hand.btn_cancel.clicked.connect(
            lambda: self.cancel_log_page())

        # Conecta os botões de idioma
        self.dlg_hand.btn_eng.clicked.connect(
            lambda: self.traduz_interface('en'))
        self.dlg_hand.btn_ptbr.clicked.connect(
            lambda: self.traduz_interface('pt'))

        # Inicializa interface em inglês
        self.traduz_interface('en')

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&HAND Plugin'),
                action)
            self.iface.removeToolBarIcon(action)

    def apaga_arquivos_temp(self):
        """Esta funcao elimina os arquivos temporarios criados durante a execucao do plugin"""
        temp_path = Path(self.diretorio_atual + r'\temp')

        # Seleciona todos os arquivos exceto o executavel
        arquivos = [f for f in temp_path.iterdir() if f.is_file()
                    and f.suffix.lower() != ".exe"]

        # Apaga todos os arquivos
        for file in arquivos:
            os.remove(file)

    def carregaArquivos(self, combobox, file_type="raster"):
        """Esta funcao é utilizada para adicionar os arquivos enviados pelo usuario ao plugin"""
        # Define as variaveis e configuracoes da janela de escolha do arquivo
        file_ = None
        options = QFileDialog.Options()

        while True:  # Loop até que o usuario selecione um arquivo ou cancele

            # Janela de dialogo com o Usuario
            if file_type == "raster":
                file_, _ = QFileDialog.getOpenFileName(
                    None, "Seleciona um arquivo!", "", "GeoTIFF (*.tif)", options=options)
                if not file_:
                    result = self.msgs[self.idioma_atual]['no_file_selected']
                    reply = QMessageBox.warning(
                        self.dlg_hand, self.msgs[self.idioma_atual]['warning_title'], result, QMessageBox.Ok)
                    if reply == QMessageBox.Ok:
                        break

                # Se o raster nao estiver no projeto, adiciona
                if file_ not in [layer.source() for layer in QgsProject.instance().mapLayers().values()]:
                    layer = QgsRasterLayer(
                        file_, os.path.basename(file_), "gdal")
                    QgsProject.instance().addMapLayer(layer)

                # Adiciona o arquivo ao combo box
                combobox.setLayer(layer)

                return file_

    def save_buttons(self):
        '''Esta funcao configura os botoes da salvar (criar arquivo)'''
        # Seleciona o arquivo enviado pelo usuario
        while True:
            file_name, _ = QFileDialog.getSaveFileName(
                None, "Salve o arquivo.", '', "GeoTIFF(*.tif)")
            if file_name:
                self.dlg_hand.le_01.setText(file_name)
                break

            else:
                # O usuario nao selecionou um arquivo (um caminho para salvar o arquivo de saida)
                result = self.msgs[self.idioma_atual]['no_file_selected']
                reply = QMessageBox.warning(
                    self.dlg_hand, self.msgs[self.idioma_atual]['warning_title'], result, QMessageBox.Ok)
                if reply == QMessageBox.Ok:
                    break

    def cancel_log_page(self):
        '''Esta funcao configura o botao de cancelar da pagina de log'''
        self.dlg_hand.te_logg.clear()
        mensagem_log1 = self.msgs[self.idioma_atual]['cancel_log']
        self.dlg_hand.te_logg.insertHtml(mensagem_log1)

        # Reativa a pagina de parametros
        self.dlg_hand.pg_parameters.setEnabled(True)

        # Desativa a pagina de logge
        self.dlg_hand.pg_log_hand.setEnabled(False)

        # Apaga arquivos criados
        self.apaga_arquivos_temp()

    def le_geotiff_escreve_bin(self):
        """Esta funcao realiza a leitura do arquivo .tif enviado pelo user e o converte em .rst tipo binary para leitura no fortran"""
        # Limpa pasta temp
        self.apaga_arquivos_temp()

        # Define os caminhos para os arquivos GeoTIFF temporários
        bacia_temp_tif = self.diretorio_atual + r'\temp\bacia_temp.tif'
        MDE_temp_tif = self.diretorio_atual + r'\temp\MDE_temp.tif'
        dir_temp_tif = self.diretorio_atual + r'\temp\dir_temp.tif'
        drenagem_temp_tif = self.diretorio_atual + r'\temp\drenagem_temp.tif'

        self.dlg_hand.progressBar.setValue(5)
        # Converte os arquivos de entrada para os tipos de dados corretos em cópias temporárias
        gdal.Translate(bacia_temp_tif, self.dlg_hand.cb_01.currentLayer(
        ).source(), outputType=gdal.GDT_Int16)

        # armazena geotransformacao e projecao
        dataset = gdal.Open(self.dlg_hand.cb_01.currentLayer().source())
        self.projection = dataset.GetProjection()
        dataset = None  # Fecha o dataset

        self.dlg_hand.progressBar.setValue(10)
        gdal.Translate(MDE_temp_tif, self.dlg_hand.cb_02.currentLayer(
        ).source(), outputType=gdal.GDT_Float32)
        self.dlg_hand.progressBar.setValue(15)
        gdal.Translate(dir_temp_tif, self.dlg_hand.cb_03.currentLayer(
        ).source(), outputType=gdal.GDT_Int16)
        self.dlg_hand.progressBar.setValue(20)
        gdal.Translate(drenagem_temp_tif, self.dlg_hand.cb_04.currentLayer(
        ).source(), outputType=gdal.GDT_Int16)
        self.dlg_hand.progressBar.setValue(25)

        # Arquivos rst bin
        bacia_rst = self.diretorio_atual + r'\temp\bacia.rst'
        MDE_rst = self.diretorio_atual + r'\temp\MDE.rst'
        dir_rst = self.diretorio_atual + r'\temp\dir.rst'
        drenagem_rst = self.diretorio_atual + r'\temp\drenagem.rst'

        # Converte as cópias temporárias para o formato RST
        gdal.Translate(bacia_rst, bacia_temp_tif, format="RST")
        self.dlg_hand.progressBar.setValue(30)

        # Converte MDE
        gdal.Translate(MDE_rst, MDE_temp_tif, format="RST")
        self.dlg_hand.progressBar.setValue(35)

        # Converte direcoes de fluxo
        gdal.Translate(dir_rst, dir_temp_tif, format="RST")
        self.dlg_hand.progressBar.setValue(40)

        # Converte rede de drenagem
        gdal.Translate(drenagem_rst, drenagem_temp_tif, format="RST")
        self.dlg_hand.progressBar.setValue(50)

    def verify_file_name(self):
        """Verifica se o nome do arquivo de saída é válido."""
        file_name = self.dlg_hand.le_01.text()
        if not file_name.lower().endswith('.tif'):
            QMessageBox.warning(
                self.dlg_hand, self.msgs[self.idioma_atual]['error_title'], self.msgs[self.idioma_atual]['invalid_filename'])
            self.dlg_hand.progressBar.setValue(0)
            return False
        return True

    def run_process_hand(self):
        """Organiza a criacao dos arquivos que serao lidos pela rotina Hand em fortran.
        Salva e adicona ao projeto atual do qgis o raster gerado"""
        if not self.verify_file_name():
            return  # Se o nome do arquivo não for válido, interrompe o processo

        # Ativiva a pagina de log e limpa as informacoes passadas no text_edit
        mensagem_log1 = None
        mensagem_log = None
        self.dlg_hand.tabWidget.setCurrentIndex(1)
        self.dlg_hand.pg_log_hand.setEnabled(True)
        self.dlg_hand.te_logg.clear()
        # Configura as informacoes do textEdit da referida pagina
        font = QFont()
        font.setPointSize(11)
        version_info = {
            "QGIS Version": '3.28.0-Firenze',
            "Qt Version": '5.15.3',
            "Python Version": '3.9.5',
            "GDAL Version": '3.8.0'}

        datatime_started = datetime.now().isoformat()
        mensagem_log1 = "The plugin was developed with:\n"
        mensagem_log1 += f"QGIS Version: {version_info['QGIS Version']}\n"
        mensagem_log1 += f"Qt Version: {version_info['Qt Version']}\n"
        mensagem_log1 += f"Python Version: {version_info['Python Version']}\n"
        mensagem_log1 += f"GDAL Version: {version_info['GDAL Version']}\n"
        mensagem_log1 += "--------------------------------------------------------\n"
        mensagem_log1 += f"Algorithm started at: {datatime_started}\n"
        mensagem_log1 += "--------------------------------------------------------\n"
        if self.idioma_atual == 'pt':
            mensagem_log1 = "O plugin foi desenvolvido com:\n"
            mensagem_log1 += f"QGIS Versão: {version_info['QGIS Version']}\n"
            mensagem_log1 += f"Qt Versão: {version_info['Qt Version']}\n"
            mensagem_log1 += f"Python Versão: {version_info['Python Version']}\n"
            mensagem_log1 += f"GDAL Versão: {version_info['GDAL Version']}\n"
            mensagem_log1 += "--------------------------------------------------------\n"
            mensagem_log1 += f"Algoritmo iniciado em: {datatime_started}\n"
            mensagem_log1 += "--------------------------------------------------------\n"
        self.dlg_hand.te_logg.append(mensagem_log1)

        # Chama funcao que converte os arquivos
        self.le_geotiff_escreve_bin()

        # Chama executavel fortran
        # Chama executavel fortrar para iniciar o processamento do hand
        mensagem_log = self.msgs[self.idioma_atual]['hand_start']
        self.dlg_hand.te_logg.append(mensagem_log)
        workdir = self.diretorio_atual + r'\temp'
        if platform.system() == "Windows":
            hand_fortran = os.path.join(
                self.diretorio_atual, "temp", "HAND.exe")
        else:
            hand_fortran = os.path.join(self.diretorio_atual, "temp", "HAND")
            subprocess.run(["chmod", "+x", hand_fortran], cwd=workdir)

        hand_exe = subprocess.run([hand_fortran], cwd=workdir)

        # verifica se houve algum erro no processamento da rotina fortran
        # Caso nao, a execucao continua no python
        if hand_exe.returncode == 0:
            mensagem_log = self.msgs[self.idioma_atual]['hand_success']
            self.dlg_hand.te_logg.append(mensagem_log)
            self.dlg_hand.progressBar.setValue(75)

            hand_out = self.diretorio_atual + r'\temp\HAND.rst'

            # Converte arquivo do hand para geotiff e adiciona ao QGIS
            if os.path.isfile(hand_out) == True and self.dlg_hand.le_01.text() is not '':
                mensagem_log = self.msgs[self.idioma_atual]['hand_convert']
                self.dlg_hand.te_logg.append(mensagem_log)
                gdal.Translate(self.dlg_hand.le_01.text(),
                               hand_out, format="GTiff", outputType=gdal.GDT_Float32, outputSRS=self.projection)
                self.dlg_hand.progressBar.setValue(90)

                # Adiciona ao qgis o resultado
                file_ = self.dlg_hand.le_01.text()

                mensagem_log = self.msgs[self.idioma_atual]['hand_add']
                self.dlg_hand.te_logg.append(mensagem_log)

                layer = QgsRasterLayer(
                    file_, os.path.basename(file_), "gdal")
                QgsProject.instance().addMapLayer(layer)

                self.dlg_hand.progressBar.setValue(100)
                mensagem_log = self.msgs[self.idioma_atual]['success_log']
                self.dlg_hand.te_logg.append(mensagem_log)

                QMessageBox.information(
                    self.dlg_hand, self.msgs[self.idioma_atual]['info_title'], self.msgs[self.idioma_atual]['success'])

                self.apaga_arquivos_temp()

            else:
                QMessageBox.warning(
                    self.dlg_hand, self.msgs[self.idioma_atual]['error_title'], self.msgs[self.idioma_atual]['invalid_path'])
                self.dlg_hand.progressBar.setValue(0)
                self.apaga_arquivos_temp()
        else:
            QMessageBox.warning(
                self.dlg_hand, self.msgs[self.idioma_atual]['error_title'], self.msgs[self.idioma_atual]['hand_error'])
            self.dlg_hand.progressBar.setValue(0)

    def run(self):
        """Run method that performs all the real work"""
        if not self.dlg_hand.isVisible():
            # Se o diálogo não estiver visível, mostre-o.
            self.dlg_hand.show()
        else:
            # Se já estiver visível, traga-o para a frente e dê o foco.
            self.dlg_hand.raise_()
            self.dlg_hand.activateWindow()
